import { OFListState } from './OFLibTypes';

export interface OFUsersByIdResponseData {
    view: string;
    avatar: string;
    avatarThumbs: {
        c50: string;
        c144: string;
    };
    header: string;
    headerSize: {
        width: number;
        height: number;
    };
    headerThumbs: {
        w480: string;
        w760: string;
    };
    id: number;
    name: string;
    username: string;
    canLookStory: boolean;
    canCommentStory: boolean;
    hasNotViewedStory: boolean;
    isVerified: boolean;
    canPayInternal: boolean;
    hasScheduledStream: boolean;
    hasStream: boolean;
    hasStories: boolean;
    tipsEnabled: boolean;
    tipsTextEnabled: boolean;
    tipsMin: number;
    tipsMinInternal: number;
    tipsMax: number;
    canEarn: boolean;
    canAddSubscriber: boolean;
    subscribePrice: number;
    isPaywallRequired: boolean;
    unprofitable: boolean;
    listsStates: OFListState[];
    isRestricted: boolean;
    canRestrict: boolean;
    subscribedBy: boolean;
    subscribedByExpire: string | null;
    subscribedByExpireDate: string | null;
    subscribedByAutoprolong: string | null;
    subscribedIsExpiredNow: string | null;
    currentSubscribePrice: number | null;
    subscribedOn: boolean;
    subscribedOnExpiredNow: string | null;
    subscribedOnDuration: string | null;
    joinDate: string;
    isReferrerAllowed: boolean;
    about: string;
    rawAbout: string;
    website: string;
    wishlist: string | null;
    location: string;
    postsCount: number;
    archivedPostsCount: number;
    privateArchivedPostsCount: number;
    photosCount: number;
    videosCount: number;
    audiosCount: number;
    mediasCount: number;
    lastSeen: string;
    favoritesCount: number;
    favoritedCount: number;
    showPostsInFeed: boolean;
    canReceiveChatMessage: boolean;
    isPerformer: boolean;
    isRealPerformer: boolean;
    isSpotifyConnected: boolean;
    subscribersCount: number | null;
    hasPinnedPosts: boolean;
    hasLabels: boolean;
    canChat: boolean;
    callPrice: number;
    isPrivateRestriction: boolean;
    showSubscribersCount: boolean;
    showMediaCount: boolean;
    subscribedByData: any | null;
    subscribedOnData: any | null;
    canPromotion: boolean;
    canCreatePromotion: boolean;
    canCreateTrial: boolean;
    isAdultContent: boolean;
    canTrialSend: boolean;
    hasLinks: boolean;
    finishedStreamsCount: number;
    shouldShowFinishedStreams: boolean;
    hasSavedStreams: boolean;
    firstPublishedPostDate: string;
    isSpringConnected: boolean;
    isFriend: boolean;
    isBlocked: boolean;
    canReport: boolean;
}
